# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1457f97610cf98fc1eaeeec8a79151e6b32e6b3ae15863ac1e04f11adc8af061a0277d61c125e5c1c5384f00257d8c1bc96d1af4314234e826bb40382cd734b

test:
  secret_key_base: 21cd5ad100b02eb113d15afc0addb2030b0e1986a5c97f0479460915edcc1d5c075710c3373d850b5b325c1be1439a91228612d3e7016788ad04c5baf2eb2cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
